### ISSUE TITLE
TypeError - Module.createRequire

### ISSUE THREAD

**Issue by Synal** [wofferl/proxmox-backup-arm64#6]
Hi,

build.sh throws an error:

`
/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:128337
const require$1 = Module.createRequire((typeof document === 'undefined' ? new ((__webpack_require__(892).URL))('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('eslintrc.cjs', document.baseURI).href)));
                         ^

TypeError: Module.createRequire is not a function
    at Object.__webpack_modules__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:128337:26)
    at __webpack_require__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134865:42)
    at Object.__webpack_modules__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:124916:5)
    at __webpack_require__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134865:42)
    at Object.__webpack_modules__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:124110:5)
    at __webpack_require__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134865:42)
    at Object.__webpack_modules__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:124078:5)
    at __webpack_require__ (/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134865:42)
    at /home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134900:37
    at /home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0/lib/eslint.js:134903:12
dh_auto_test: /usr/bin/node -e require\(\"./.\"\) returned exit code 1
make[1]: *** [debian/rules:4: build] Error 2
make[1]: Leaving directory '/home/synal/proxmox-backup-arm64/sources/pve-eslint/pve-eslint-8.4.0'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:37: pve-eslint_8.4.0-2_all.deb] Error 2
`

[build.log](https://github.com/wofferl/proxmox-backup-arm64/files/7994668/build.log)
 
OrangePi 3 
Armbian 21.08.8 with Linux 5.10.60-sunxi64

Can you help me with that?

**Comment by Synal** [comment]
you mean nodejs? 10.24.0
`synal@orangepi3:~/pve-eslint$ sudo apt install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (10.24.0~dfsg-1~deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by wofferl** [comment]
You need at least v12.2.0 (https://nodejs.org/api/module.html#modulecreaterequirefilename).

Proxmox Backup Server 2.x is based on Debian Bullseye, so there might be more issues if your armbian is based on an older version.
